parameters:
services:
    odiseo_blog.gaufrette:
        class: Gaufrette\Filesystem
        arguments: ["odiseo_blog_image"]
        factory:
            - '@knp_gaufrette.filesystem_map'
            - 'get'

    odiseo_blog.image_uploader:
        class: Odiseo\BlogBundle\Uploader\ImageUploader
        arguments: ["@odiseo_blog.gaufrette"]

    odiseo_blog.factory.article_comment:
        class: Odiseo\BlogBundle\Factory\ArticleCommentFactory
        arguments:
            - "%odiseo_blog.model.article_comment.class%"
            - "@odiseo_blog.repository.article"
            - "@odiseo_blog.repository.article_comment"

    # FORM TYPES
    odiseo_blog.form.type.article:
        class: Odiseo\BlogBundle\Form\Type\ArticleType
        arguments: ['%odiseo_blog.model.article.class%', ['odiseo']]
        tags:
            - { name: form.type, alias: odiseo_blog_article }

    odiseo_blog.form.type.article_translation:
        class: Odiseo\BlogBundle\Form\Type\ArticleTranslationType
        arguments: ['%odiseo_blog.model.article_translation.class%', ['odiseo']]
        tags:
            - { name: form.type, alias: odiseo_blog_article_translation }

    odiseo_blog.form.type.article_category:
        class: Odiseo\BlogBundle\Form\Type\ArticleCategoryType
        arguments: ['%odiseo_blog.model.article_category.class%', ['odiseo']]
        tags:
            - { name: form.type, alias: odiseo_blog_article_category }

    odiseo_blog.form.type.article_category_translation:
        class: Odiseo\BlogBundle\Form\Type\ArticleCategoryTranslationType
        arguments: ['%odiseo_blog.model.article_category_translation.class%', ['odiseo']]
        tags:
            - { name: form.type, alias: odiseo_blog_article_category_translation }

    odiseo_blog.form.type.article_comment:
        class: Odiseo\BlogBundle\Form\Type\ArticleCommentType
        arguments: ['%odiseo_blog.model.article_comment.class%', ['odiseo']]
        tags:
            - { name: form.type, alias: odiseo_blog_article_comment }

    odiseo_blog.form.type.article_user_comment:
        class: Odiseo\BlogBundle\Form\Type\ArticleUserCommentType
        arguments: ['%odiseo_blog.model.article_comment.class%', ['odiseo']]
        tags:
            - { name: form.type, alias: odiseo_blog_article_user_comment }

    odiseo_blog.form.type.article_image:
        class: Odiseo\BlogBundle\Form\Type\ArticleImageType
        arguments: ['%odiseo_blog.model.article_image.class%', ['odiseo']]
        tags:
            - { name: form.type, alias: odiseo_blog_article_image }

    # LISTENERS
    odiseo_blog.listener.article_image_upload:
        class: Odiseo\BlogBundle\EventListener\ArticleImageUploadListener
        arguments:
            - "@odiseo_blog.image_uploader"
        tags:
            - { name: kernel.event_listener, event: odiseo_blog.article.pre_create, method: uploadImages }
            - { name: kernel.event_listener, event: odiseo_blog.article.pre_update, method: uploadImages }